export interface Tool {
  id: string;
  name: string;
  description: string;
  icon: string;
  route: string;
  categories: string[]; // Array of category IDs from categories: Category[]
  keywords: string[];
  isPopular?: boolean;
  isNew?: boolean;
  searchVolume: number;
  label?: 'popular' | 'new' | 'coming-soon' | 'test' | ''; // Tool label for badges
}

export interface Category {
  id: string;
  name: string;
  description: string;
  icon: string;
  tools: Tool[];
}

// Tool data
export const tools: Tool[] = [
  // Data & Conversion Tools
  {
    id: 'json-formatter',
    name: 'JSON Formatter',
    description:
      'Format, validate and beautify JSON data with syntax highlighting',
    icon: '📋',
    route: '/tools/json-formatter',
    categories: ['data', 'formatters'],
    keywords: ['json', 'format', 'validate', 'prettify', 'parse'],
    isPopular: true,
    searchVolume: 8500,
    label: '',
  },
  {
    id: 'csv-to-json',
    name: 'CSV to JSON',
    description: 'Convert CSV files to JSON format with customizable options',
    icon: '🔄',
    route: '/tools/csv-to-json',
    categories: ['data'],
    keywords: [
      'csv',
      'json',
      'convert',
      'data',
      'transform',
      'spreadsheet',
      'excel',
    ],
    isPopular: true,
    searchVolume: 7200,
    label: '',
  },
  {
    id: 'json-to-csv',
    name: 'JSON to CSV Converter',
    description:
      'Convert JSON to CSV with advanced formatting, flattening, and column mapping options',
    icon: '📊',
    route: '/tools/json-to-csv',
    categories: ['data', 'dev'],
    keywords: [
      'json to csv',
      'json converter',
      'convert json to excel',
      'json to csv online',
      'json parser',
      'json',
      'csv',
      'excel',
      'spreadsheet',
      'export',
      'data transformation',
      'flatten json',
      'json array',
      'tabular data',
    ],
    isPopular: true,
    searchVolume: 25000,
    label: '',
  },
  {
    id: 'sql-formatter',
    name: 'SQL Formatter',
    description: 'Format and beautify SQL queries with proper indentation',
    icon: '🗃️',
    route: '/tools/sql-formatter',
    categories: ['formatters', 'data', 'text'],
    keywords: ['sql', 'format', 'database', 'query', 'beautify'],
    searchVolume: 6800,
    label: '',
  },
  {
    id: 'xml-formatter',
    name: 'XML Formatter',
    description:
      'Format, validate, and minify XML documents with syntax highlighting and XPath support',
    icon: '📄',
    route: '/tools/xml-formatter',
    categories: ['formatters', 'data'],
    keywords: [
      'xml',
      'formatter',
      'beautify',
      'minify',
      'validate',
      'parser',
      'xpath',
      'namespace',
      'schema',
      'soap',
      'rss',
      'svg',
      'markup',
      'xsd',
      'dtd',
    ],
    isPopular: true,
    searchVolume: 8900,
    label: '',
  },
  {
    id: 'xml-to-json-converter',
    name: 'XML to JSON Converter',
    description:
      'Convert XML documents to JSON format with attribute handling, namespace support, and smart array detection',
    icon: '🔄',
    route: '/tools/xml-to-json-converter',
    categories: ['data', 'formatters'],
    keywords: [
      'xml to json',
      'xml converter',
      'convert xml to json',
      'xml parser',
      'xml',
      'json',
      'converter',
      'parser',
      'namespace',
      'attributes',
      'cdata',
      'soap to json',
      'rss to json',
      'api',
      'data transformation',
    ],
    isPopular: true,
    searchVolume: 12500,
    label: '',
  },

  // Encoding & Security Tools
  {
    id: 'base64-encode',
    name: 'Base64 Encoder/Decoder',
    description: 'Encode and decode Base64 strings with file support',
    icon: '🔐',
    route: '/tools/base64-encode',
    categories: ['encoding'],
    keywords: ['base64', 'encode', 'decode', 'encryption', 'security'],
    isPopular: true,
    searchVolume: 9200,
    label: '',
  },
  {
    id: 'url-encode',
    name: 'URL Encoder/Decoder',
    description: 'Encode and decode URL components and query parameters',
    icon: '🔗',
    route: '/tools/url-encode',
    categories: ['encoding'],
    keywords: ['url', 'encode', 'decode', 'percent', 'uri'],
    isPopular: true,
    searchVolume: 7800,
    label: '',
  },
  {
    id: 'html-encode-decode',
    name: 'HTML Encoder/Decoder',
    description:
      'Convert text to HTML entities and decode HTML entities to plain text',
    icon: '🏷️',
    route: '/tools/html-encode-decode',
    categories: ['encoding', 'text'],
    keywords: [
      'html',
      'encode',
      'decode',
      'entities',
      'escape',
      'unescape',
      'sanitize',
      'xss',
      'special characters',
      'xml',
    ],
    isNew: true,
    searchVolume: 6200,
    label: '',
  },
  {
    id: 'hash-generator',
    name: 'Hash Generator',
    description: 'Generate MD5, SHA1, SHA256 and other hash functions',
    icon: '#️⃣',
    route: '/tools/hash-generator',
    categories: ['encoding'],
    keywords: ['hash', 'md5', 'sha1', 'sha256', 'checksum'],
    isPopular: true,
    searchVolume: 6500,
    label: '',
  },
  {
    id: 'jwt-decoder',
    name: 'JWT Decoder',
    description: 'Decode and validate JSON Web Tokens (JWT)',
    icon: '🎫',
    route: '/tools/jwt-decoder',
    categories: ['encoding'],
    keywords: ['jwt', 'json', 'web', 'token', 'decode'],
    isNew: true,
    searchVolume: 5800,
    label: '',
  },
  {
    id: 'base64-to-pdf',
    name: 'Base64 to PDF',
    description: 'Convert Base64 encoded data to PDF files and download them',
    icon: '📄',
    route: '/tools/base64-to-pdf',
    categories: ['base64', 'data'],
    keywords: ['base64', 'pdf', 'convert', 'download', 'decode', 'file'],
    searchVolume: 3200,
    label: '',
  },
  {
    id: 'base64-to-gif',
    name: 'Base64 to GIF',
    description:
      'Convert Base64 encoded data to GIF images and download them with preview',
    icon: '🎞️',
    route: '/tools/base64-to-gif',
    categories: ['base64', 'data'],
    keywords: [
      'base64',
      'gif',
      'image',
      'convert',
      'download',
      'decode',
      'animation',
    ],
    searchVolume: 2800,
    label: '',
  },
  {
    id: 'excel-filter',
    name: 'Excel Filter Tool',
    description:
      'Upload Excel files and apply dynamic filters to tables with search, sort, and export capabilities',
    icon: '📊',
    route: '/tools/excel-filter',
    categories: ['data'],
    keywords: [
      'excel',
      'filter',
      'spreadsheet',
      'table',
      'data',
      'search',
      'sort',
      'export',
      'csv',
      'xlsx',
      'query',
      'analyze',
      'viewer',
      'browser',
      'online',
    ],
    searchVolume: 8500,
    label: '',
  },

  // Text & Format Tools
  {
    id: 'instagram-font-generator',
    name: 'Instagram Font Generator',
    description:
      'Generate stylized Unicode fonts for Instagram, WhatsApp, and social media bios',
    icon: '✨',
    route: '/tools/instagram-font-generator',
    categories: ['social', 'text'],
    keywords: [
      'instagram',
      'font',
      'generator',
      'unicode',
      'text',
      'style',
      'fancy',
      'bio',
      'whatsapp',
      'social',
      'media',
      'bold',
      'italic',
      'cursive',
      'monospace',
      'aesthetic',
      'fonts for instagram',
      'instagram bio fonts',
      'fancy text generator',
      'unicode text',
      'stylish text',
      'cool fonts',
      'text decorator',
    ],
    isPopular: true,
    searchVolume: 82000,
    label: '',
  },
  {
    id: 'text-diff',
    name: 'Text Diff Checker',
    description:
      'Compare files and code with advanced diff features and syntax highlighting',
    icon: '📝',
    route: '/tools/text-diff',
    categories: ['text', 'dev'],
    keywords: [
      'diff',
      'compare',
      'text',
      'difference',
      'merge',
      'patch',
      'git',
      'code',
      'file',
    ],
    searchVolume: 5200,
    label: '',
  },
  {
    id: 'markdown-preview',
    name: 'Markdown Preview',
    description: 'Preview and convert Markdown to HTML in real-time',
    icon: '📖',
    route: '/tools/markdown-preview',
    categories: ['text'],
    keywords: ['markdown', 'preview', 'html', 'convert', 'format'],
    searchVolume: 4800,
    label: 'coming-soon',
  },
  {
    id: 'regex-tester',
    name: 'Regex Tester',
    description: 'Test and debug regular expressions with live matching',
    icon: '🔍',
    route: '/tools/regex-tester',
    categories: ['text'],
    keywords: ['regex', 'regexp', 'pattern', 'test', 'match'],
    isPopular: true,
    searchVolume: 7500,
    label: '',
  },

  // Generators
  {
    id: 'uuid-generator',
    name: 'UUID Generator',
    description: 'Generate UUID/GUID in various formats (v1, v4, etc.)',
    icon: '🆔',
    route: '/tools/uuid-generator',
    categories: ['generators'],
    keywords: ['uuid', 'guid', 'generate', 'unique', 'identifier'],
    isPopular: true,
    searchVolume: 8200,
    label: '',
  },
  {
    id: 'password-generator',
    name: 'Password Generator',
    description: 'Generate secure passwords with customizable options',
    icon: '🔑',
    route: '/tools/password-generator',
    categories: ['generators'],
    keywords: ['password', 'generate', 'secure', 'random', 'strong'],
    isPopular: true,
    searchVolume: 9500,
    label: '',
  },
  {
    id: 'qr-generator',
    name: 'QR Code Generator',
    description:
      'Generate QR codes with advanced customization, logos, batch processing and developer tools',
    icon: '📱',
    route: '/tools/qr-generator',
    categories: ['generators', 'dev', 'web'],
    keywords: [
      'qr',
      'code',
      'generate',
      'barcode',
      'scan',
      'wifi',
      'vcard',
      'batch',
      'svg',
      'logo',
      'api',
      'developer',
    ],
    isPopular: true,
    searchVolume: 9800,
    label: '',
  },

  // Web & Design Tools
  {
    id: 'color-picker',
    name: 'Color Picker',
    description:
      'Professional color picker with palettes, contrast checker and format conversion',
    icon: '🎨',
    route: '/tools/color-picker',
    categories: ['web', 'dev'],
    keywords: [
      'color',
      'picker',
      'hex',
      'rgb',
      'hsl',
      'hsv',
      'cmyk',
      'palette',
      'generator',
      'contrast',
      'checker',
      'wcag',
      'accessibility',
      'css',
      'tailwind',
      'material',
      'design',
      'eyedropper',
      'gradient',
      'harmony',
      'complementary',
      'triadic',
      'analogous',
      'color blindness',
      'lab',
      'pantone',
    ],
    isPopular: true,
    searchVolume: 12500,
    label: '',
  },
  {
    id: 'color-format-converter',
    name: 'Color Format Converter',
    description:
      'Convert colors between HEX, RGB, HSL, HSV, and CMYK formats with palette generation and contrast checker',
    icon: '🌈',
    route: '/tools/color-format-converter',
    categories: ['web', 'generators', 'dev'],
    keywords: [
      'color converter',
      'hex to rgb',
      'rgb to hex',
      'hsl to hex',
      'hsv to rgb',
      'cmyk converter',
      'color format',
      'hex converter',
      'rgb converter',
      'color code',
      'color transformation',
      'color palette generator',
      'color shades',
      'color tints',
      'wcag contrast',
      'accessibility',
      'css colors',
      'color picker',
      'web colors',
      'design colors',
    ],
    isPopular: true,
    searchVolume: 18500,
    label: '',
  },
  {
    id: 'image-optimizer',
    name: 'Image Optimizer',
    description: 'Compress and optimize images for web use',
    icon: '🖼️',
    route: '/tools/image-optimizer',
    categories: ['web'],
    keywords: ['image', 'optimize', 'compress', 'resize', 'webp'],
    isNew: true,
    searchVolume: 4500,
    label: 'coming-soon',
  },
  {
    id: 'favicon-generator',
    name: 'Favicon Generator',
    description:
      'Generate complete favicon packages with all sizes and formats',
    icon: '🖥️',
    route: '/tools/favicon-generator',
    categories: ['web', 'generators'],
    keywords: [
      'favicon',
      'icon',
      'apple-touch-icon',
      'android-chrome',
      'website-icon',
      'ico',
      'png',
      'image',
    ],
    isNew: true,
    searchVolume: 3200,
    label: '',
  },
  {
    id: 'gradient-generator',
    name: 'Gradient Generator',
    description:
      'Create beautiful CSS gradients with visual editor, presets and real-time preview',
    icon: '🌈',
    route: '/tools/gradient-generator',
    categories: ['web', 'generators'],
    keywords: [
      'gradient',
      'css',
      'linear',
      'radial',
      'conic',
      'color',
      'background',
      'design',
      'web',
      'ui',
      'tailwind',
      'svg',
      'maker',
      'tool',
      'generator',
    ],
    isPopular: true,
    searchVolume: 15000,
    label: '',
  },

  // Dev Utilities
  {
    id: 'api-tester',
    name: 'API Tester',
    description: 'Test REST APIs with custom headers and body',
    icon: '🔧',
    route: '/tools/api-tester',
    categories: ['dev'],
    keywords: ['api', 'rest', 'test', 'http', 'request'],
    searchVolume: 6800,
    label: 'coming-soon',
  },
  {
    id: 'json-validator',
    name: 'JSON Validator',
    description:
      'Advanced JSON validation with schema support, error reporting, and security checks',
    icon: '✅',
    route: '/tools/json-validator',
    categories: ['dev', 'data'],
    keywords: [
      'json',
      'validator',
      'schema',
      'validate',
      'check',
      'format',
      'jsonschema',
      'draft',
      'parser',
      'syntax',
      'error',
      'linter',
      'api',
      'development',
      'security',
      'audit',
      'compliance',
      'structure',
      'verification',
      'testing',
    ],
    isPopular: true,
    searchVolume: 8400,
    label: '',
  },
  {
    id: 'crontab-builder',
    name: 'Crontab Expression Builder',
    description:
      'Parse, build, and validate cron expressions with visual builder, presets, and next execution times',
    icon: '⏰',
    route: '/tools/crontab-builder',
    categories: ['dev'],
    keywords: [
      'crontab',
      'cron',
      'scheduler',
      'unix',
      'linux',
      'automation',
      'parser',
      'builder',
      'expression',
    ],
    isPopular: true,
    searchVolume: 5500,
    label: '',
  },
  {
    id: 'list-compare',
    name: 'List Compare & Diff Tool',
    description:
      'Advanced list comparison with set operations, fuzzy matching, and developer-friendly output formats',
    icon: '📋',
    route: '/tools/list-compare',
    categories: ['dev', 'text'],
    keywords: [
      'list compare',
      'diff lists',
      'set operations',
      'compare arrays',
      'list difference',
      'intersection',
      'union',
      'venn diagram',
      'array diff',
      'list merger',
      'duplicate finder',
      'fuzzy matching',
      'string comparison',
      'data analysis',
      'csv compare',
      'json compare',
      'package dependencies',
      'git files',
      'code compare',
    ],
    isPopular: true,
    searchVolume: 18000,
    label: '',
  },
  {
    id: 'curl-to-code',
    name: 'cURL to Code Converter',
    description:
      'Convert cURL commands to production-ready code in any programming language with error handling and type safety',
    icon: '🔄',
    route: '/tools/curl-to-code',
    categories: ['dev', 'generators', 'data'],
    keywords: [
      'curl to code',
      'curl converter',
      'curl to javascript',
      'curl to python',
      'http client generator',
      'api code generator',
      'curl to axios',
      'curl to fetch',
      'curl to golang',
      'curl to java',
      'curl to csharp',
      'curl to php',
      'curl to ruby',
      'rest api converter',
      'http request converter',
      'postman to code',
      'har to code',
      'api client generator',
      'sdk generator',
    ],
    isPopular: true,
    searchVolume: 45000,
    label: '',
  },
  {
    id: 'json-to-typescript',
    name: 'JSON to TypeScript Converter',
    description:
      'Convert JSON to TypeScript interfaces with smart type inference, optional properties, and nested interface support',
    icon: '🔧',
    route: '/tools/json-to-typescript',
    categories: ['data', 'dev', 'generators'],
    keywords: [
      'json to typescript',
      'typescript interface generator',
      'json to interface',
      'type generator',
      'typescript types from json',
      'interface generator',
      'typescript converter',
      'json parser',
      'type inference',
      'typescript definitions',
      'api types',
      'type safety',
      'typescript interfaces',
      'json schema',
      'type generation',
      'developer tools',
      'code generator',
      'typescript typing',
      'json typing',
      'interface extractor',
    ],
    isPopular: true,
    searchVolume: 35000,
    label: '',
  },
  {
    id: 'css-minifier',
    name: 'CSS Minifier/Beautifier',
    description:
      'Minify, beautify and optimize CSS code with advanced compression options for production-ready stylesheets',
    icon: '🎨',
    route: '/tools/css-minifier',
    categories: ['formatters', 'dev', 'web'],
    keywords: [
      'css minifier',
      'css beautifier',
      'css formatter',
      'css compressor',
      'minimize css',
      'css optimization',
      'reduce css size',
      'css prettify',
      'css minify',
      'compress css',
      'css optimizer',
      'css cleaner',
      'production css',
      'css tools',
    ],
    isPopular: true,
    searchVolume: 15000,
    label: '',
  },
  {
    id: 'js-minifier',
    name: 'JavaScript Minifier/Beautifier',
    description:
      'Minify, beautify and optimize JavaScript code with ES6+ support, source maps, and advanced compression',
    icon: '⚡',
    route: '/tools/js-minifier',
    categories: ['formatters', 'dev'],
    keywords: [
      'javascript minifier',
      'js minifier',
      'javascript beautifier',
      'js formatter',
      'compress javascript',
      'minify js',
      'javascript optimizer',
      'js compression',
      'uglify js',
      'terser',
      'webpack optimizer',
      'production js',
      'bundle size',
      'tree shaking',
      'dead code elimination',
      'source maps',
      'obfuscation',
      'es6 minifier',
      'modern javascript',
    ],
    isPopular: true,
    searchVolume: 22000,
    label: '',
  },
  {
    id: 'yaml-json-converter',
    name: 'YAML to JSON Converter',
    description:
      'Convert between YAML and JSON formats with validation, type handling, and advanced formatting',
    icon: '🔄',
    route: '/tools/yaml-json-converter',
    categories: ['data', 'formatters'],
    keywords: [
      'yaml',
      'json',
      'converter',
      'parser',
      'formatter',
      'yaml to json',
      'json to yaml',
      'data transformation',
      'config converter',
      'kubernetes',
      'docker',
      'docker compose',
      'ci cd',
      'github actions',
      'ansible',
      'swagger',
      'openapi',
      'multi document',
      'anchors',
      'aliases',
    ],
    isPopular: true,
    searchVolume: 30000,
    label: '',
  },
  {
    id: 'unix-timestamp-converter',
    name: 'Unix Timestamp Converter',
    description:
      'Convert between Unix timestamps and human-readable dates with timezone support and batch processing',
    icon: '⏰',
    route: '/tools/unix-timestamp-converter',
    categories: ['data', 'dev'],
    keywords: [
      'unix',
      'timestamp',
      'epoch',
      'converter',
      'date',
      'time',
      'timezone',
      'utc',
      'milliseconds',
      'batch',
      'convert',
      'unix time',
      'epoch time',
      'datetime',
      'iso',
      'rfc',
      'posix',
    ],
    isPopular: true,
    searchVolume: 15000,
    label: '',
  },
  {
    id: 'eml-to-html',
    name: 'EML to HTML Converter',
    description:
      'Convert EML email files to HTML with header extraction, attachment handling, and multi-view rendering',
    icon: '📧',
    route: '/tools/eml-to-html',
    categories: ['data', 'dev', 'formatters'],
    keywords: [
      'eml',
      'email',
      'html',
      'converter',
      'mime',
      'rfc822',
      'email parser',
      'eml viewer',
      'email to html',
      'email converter',
      'mime parser',
      'email headers',
      'email attachments',
      'email migration',
      'email forensics',
      'email template',
      'mailbox',
      'outlook',
      'thunderbird',
      'message',
      'rfc2822',
      'multipart',
      'base64',
      'quoted-printable',
    ],
    isPopular: true,
    searchVolume: 12000,
    label: '',
  },
  {
    id: 'ai-prompt-token-counter',
    name: 'AI Prompt Token Counter',
    description:
      'Count tokens for AI prompts across GPT-4, Claude, Llama models with cost estimation and optimization',
    icon: '🤖',
    route: '/tools/ai-prompt-token-counter',
    categories: ['dev', 'generators', 'text'],
    keywords: [
      'token counter',
      'gpt token calculator',
      'claude tokens',
      'prompt tokens',
      'ai cost calculator',
      'token estimator',
      'openai tokens',
      'gpt-4 tokens',
      'llama tokens',
      'token count',
      'tokenizer',
      'api cost',
      'prompt optimization',
      'context window',
      'tiktoken',
      'ai pricing',
      'token visualization',
      'batch token count',
      'prompt engineering',
    ],
    isPopular: true,
    searchVolume: 35000,
    label: '',
  },

  // PDF Tools
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description:
      'Convert PDF files to editable Word (DOCX) format with preserved formatting',
    icon: '📄',
    route: '/tools/pdf-to-word',
    categories: ['pdf'],
    keywords: [
      'pdf',
      'word',
      'docx',
      'convert',
      'converter',
      'pdf to word',
      'pdf to docx',
      'document',
      'edit',
      'format',
      'export',
      'transformation',
      'office',
      'microsoft word',
      'libre office',
      'editable',
    ],
    isPopular: true,
    searchVolume: 12000,
    label: '',
  },
];

// Group tools by category
export const categories: Category[] = [
  {
    id: 'data',
    name: 'Data & Conversion',
    description:
      'Transform and format data between different formats like JSON, CSV, XML, and SQL.',
    icon: '📊',
    tools: getToolsByCategory('data'),
  },
  {
    id: 'encoding',
    name: 'Encoding & Security',
    description:
      'Encode, decode, hash, and secure your data with various encryption methods.',
    icon: '🔐',
    tools: getToolsByCategory('encoding'),
  },
  {
    id: 'base64',
    name: 'Base64',
    description:
      'Convert Base64 encoded data to PDF, images, and other file formats with instant download and preview.',
    icon: '🔤',
    tools: getToolsByCategory('base64'),
  },
  {
    id: 'text',
    name: 'Text & Format',
    description:
      'Process, compare, and format text content with powerful text manipulation tools.',
    icon: '📝',
    tools: getToolsByCategory('text'),
  },
  {
    id: 'generators',
    name: 'Generators',
    description:
      'Generate UUIDs, passwords, QR codes, and other useful content for development.',
    icon: '⚡',
    tools: getToolsByCategory('generators'),
  },
  {
    id: 'web',
    name: 'Web & Design',
    description:
      'Tools for web developers and designers including color pickers and image optimization.',
    icon: '🎨',
    tools: getToolsByCategory('web'),
  },
  {
    id: 'dev',
    name: 'Dev Utilities',
    description:
      'Development utilities for testing APIs, validating schemas, and debugging code.',
    icon: '🔧',
    tools: getToolsByCategory('dev'),
  },
  {
    id: 'formatters',
    name: 'Formatters',
    description:
      'Format and beautify code, SQL, JSON, XML and other structured data.',
    icon: '🪄',
    tools: getToolsByCategory('formatters'),
  },
  {
    id: 'social',
    name: 'Social Media',
    description:
      'Tools for social media content creation, including Instagram, WhatsApp, Twitter, and Facebook.',
    icon: '📱',
    tools: getToolsByCategory('social'),
  },
  {
    id: 'pdf',
    name: 'PDF Tools',
    description:
      'Professional PDF tools for conversion, editing, merging, splitting and optimization.',
    icon: '📄',
    tools: getToolsByCategory('pdf'),
  },
];

// Helper functions
export function getPopularTools(): Tool[] {
  return tools
    .filter((tool) => tool.isPopular)
    .sort((a, b) => b.searchVolume - a.searchVolume)
    .map((tool) => ({
      ...tool,
      keywords: tool.keywords || [], // Ensure keywords is always an array
    }));
}

export function searchTools(query: string): Tool[] {
  const searchTerm = query.toLowerCase();
  return tools
    .filter(
      (tool) =>
        tool.label !== 'coming-soon' &&
        (tool.name.toLowerCase().includes(searchTerm) ||
          tool.description.toLowerCase().includes(searchTerm) ||
          tool.keywords.some((keyword) =>
            keyword.toLowerCase().includes(searchTerm)
          ))
    )
    .sort((a, b) => b.searchVolume - a.searchVolume);
}

export function getToolsByCategory(categoryId: string): Tool[] {
  return tools
    .filter((tool) => {
      return tool.categories.includes(categoryId);
    })
    .sort((a, b) => {
      // First sort by searchVolume (descending), then by name (ascending) for deterministic order
      if (b.searchVolume !== a.searchVolume) {
        return b.searchVolume - a.searchVolume;
      }
      return a.name.localeCompare(b.name);
    });
}

export function getToolById(id: string): Tool | undefined {
  return tools.find((tool) => tool.id === id);
}

export function getCategoryColorClass(categoryColor: string): string {
  const colorClasses = {
    data: 'border-blue-500 bg-blue-50 dark:bg-blue-950',
    encoding: 'border-green-500 bg-green-50 dark:bg-green-950',
    text: 'border-purple-500 bg-purple-50 dark:bg-purple-950',
    generators: 'border-orange-500 bg-orange-50 dark:bg-orange-950',
    web: 'border-pink-500 bg-pink-50 dark:bg-pink-950',
    dev: 'border-yellow-500 bg-yellow-50 dark:bg-yellow-950',
    formatters: 'border-indigo-500 bg-indigo-50 dark:bg-indigo-950',
    social: 'border-rose-500 bg-rose-50 dark:bg-rose-950',
    pdf: 'border-red-500 bg-red-50 dark:bg-red-950',
  };
  return (
    colorClasses[categoryColor as keyof typeof colorClasses] ||
    'border-blue-500 bg-blue-50 dark:bg-blue-950'
  );
}

export function getCategoryByTool(tool: Tool): Category | undefined {
  return categories.find((category) =>
    category.tools.some((t) => t.id === tool.id)
  );
}

export function getAllTools(): Tool[] {
  return tools;
}
