/**
 * Dictionary sections for EN locale
 * Auto-generated by scripts/split-dictionaries.js
 */

export { default as common } from './common.json';
export { default as home } from './home.json';
export { default as tools } from './tools.json';
export { default as categories } from './categories.json';
export { default as footer } from './footer.json';
export { default as seo } from './seo.json';
export { default as lab } from './lab.json';

/**
 * Load all sections (for backward compatibility)
 */
export async function loadAll() {
  const [common, home, tools, categories, footer, seo, lab] = await Promise.all(
    [
      import('./common.json').then((m) => m.default),
      import('./home.json').then((m) => m.default),
      import('./tools.json').then((m) => m.default),
      import('./categories.json').then((m) => m.default),
      import('./footer.json').then((m) => m.default),
      import('./seo.json').then((m) => m.default),
      import('./lab.json').then((m) => m.default),
    ]
  );

  return {
    ...common,
    ...home,
    ...tools,
    ...categories,
    ...footer,
    ...seo,
    ...lab,
  };
}
